### ISSUE TITLE
Bug: Transistion from PersistentVector to SmallPersistentVector on removing an element fails

### ISSUE THREAD

**Issue by mschirmacher** [Kotlin/kotlinx.collections.immutable#78]
Tested with '0.3.2'
```
    @Test
    fun foo() {
        Array(33) { "" }
            .asList()
            .toPersistentList()
            .removeAt(32)
    }
```

Results in:
```
Assertion failed
java.lang.AssertionError: Assertion failed
	at kotlinx.collections.immutable.internal.CommonFunctionsKt.assert(commonFunctions.kt:8)
	at kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.<init>(SmallPersistentVector.kt:18)
	at kotlinx.collections.immutable.implementations.immutableList.PersistentVector.pullLastBufferFromRoot(PersistentVector.kt:183)
	at kotlinx.collections.immutable.implementations.immutableList.PersistentVector.removeFromTailAt(PersistentVector.kt:162)
	at kotlinx.collections.immutable.implementations.immutableList.PersistentVector.removeAt(PersistentVector.kt:151)
```

**Comment by qurbonzoda** [comment]
This problem was filed before (https://github.com/Kotlin/kotlinx.collections.immutable/issues/75) is already fixed in master.
Thank you for your feedback!
Please feel free to open issues for any other problems you face with the project.
